<?php

/**
 * @file
 * Module file.
 */

/**
 * Implements hook_islandora_oai_identify_request_handler().
 *
 * This custom request handler reuses all of the requests defined in
 * islandora_oai_islandora_oai_identify_request_handler() other than
 * 'response_xml'.
 */
function islandora_oai_download_link_islandora_oai_identify_request_handler() {
  return array(
    'islandora_oai_download_link' => array(
      'label' => t('Islandora OAI with download link'),
      'description' => t("Adds a direct download link to the standard OAI implementation for Islandora's OAI DC."),
      'configuration' => 'admin/islandora/tools/islandora-oai/handler',
      'requests' => array(
        'ListIdentifiers' => array(
          'file' => drupal_get_path('module', 'islandora_oai') . '/includes/handler.inc',
          'function' => 'islandora_oai_retrieve_records_or_identifiers',
        ),
        'ListRecords' => array(
          'file' => drupal_get_path('module', 'islandora_oai') . '/includes/handler.inc',
          'function' => 'islandora_oai_retrieve_records_or_identifiers',
        ),
        'ListSets' => array(
          'file' => drupal_get_path('module', 'islandora_oai') . '/includes/handler.inc',
          'function' => 'islandora_oai_retrieve_sets',
        ),
        'GetRecord' => array(
          'file' => drupal_get_path('module', 'islandora_oai') . '/includes/handler.inc',
          'function' => 'islandora_oai_retrieve_record',
        ),
        // This is the only function specific to this module.
        'response_xml' => array(
          'file' => drupal_get_path('module', 'islandora_oai_download_link') . '/includes/handler.inc',
          'function' => 'islandora_oai_download_link_object_response_xml',
        ),
        'set_membership' => array(
          'file' => drupal_get_path('module', 'islandora_oai') . '/includes/handler.inc',
          'function' => 'islandora_oai_get_membership',
        ),
      ),
    ),
  );
}

/**
 * Implements hook_form_alter().
 *
 * Not working for some reason...
 */
function islandora_oai_download_link_form_islandora_oai_handler_configuration_form_alter(&$form, $form_state, $form_id) {
  $form['islandora_oai_download_link_allowed_ips'] = array(
    'type' => 'textarea',
    '#title' => t('Allowed IP ranges'),
    '#description' => t('Enter the IP address ranges, one per line, that are allowed to view objects. ' .
      'Separate the low and high ends of each range with a colon, e.g. 111.111.111.111:222.222.222.222. ' .
      ' Asterisks are not allowed. Single IP addresses are also allowed, each on its own line.'),
      '#default_value' => variable_get('islandora_oai_download_link_allowed_ips', ''),
  );
}
