<?php

/**
 * @file
 * Module file.
 */

/**
 * Implements hook_islandora_oai_identify_request_handler().
 *
 * This custom request handler reuses all of the requests defined in
 * islandora_oai_islandora_oai_identify_request_handler() other than
 * 'response_xml'.
 */
function islandora_oai_download_link_islandora_oai_identify_request_handler() {
  return array(
    'islandora_oai_download_link' => array(
      'label' => t('Islandora OAI with download link'),
      'description' => t("Adds a direct download link to the standard OAI implementation for Islandora's OAI DC and MODS."),
      'configuration' => 'admin/islandora/tools/islandora-oai/handler',
      'requests' => array(
        'ListIdentifiers' => array(
          'file' => drupal_get_path('module', 'islandora_oai') . '/includes/handler.inc',
          'function' => 'islandora_oai_retrieve_records_or_identifiers',
        ),
        'ListRecords' => array(
          'file' => drupal_get_path('module', 'islandora_oai') . '/includes/handler.inc',
          'function' => 'islandora_oai_retrieve_records_or_identifiers',
        ),
        'ListSets' => array(
          'file' => drupal_get_path('module', 'islandora_oai') . '/includes/handler.inc',
          'function' => 'islandora_oai_retrieve_sets',
        ),
        'GetRecord' => array(
          'file' => drupal_get_path('module', 'islandora_oai') . '/includes/handler.inc',
          'function' => 'islandora_oai_retrieve_record',
        ),
        // This is the only function specific to this module.
        'response_xml' => array(
          'file' => drupal_get_path('module', 'islandora_oai_download_link') . '/includes/handler.inc',
          'function' => 'islandora_oai_download_link_object_response_xml',
        ),
        'set_membership' => array(
          'file' => drupal_get_path('module', 'islandora_oai') . '/includes/handler.inc',
          'function' => 'islandora_oai_get_membership',
        ),
      ),
    ),
  );
}

/**
 * Implements hook_form_alter().
 */
function islandora_oai_download_link_form_islandora_oai_handler_configuration_form_alter(&$form, $form_state, $form_id) {
  module_load_include('inc', 'islandora_oai_download_link', 'includes/handler');
  $form['islandora_oai_download_links'] = array(
    '#type' => 'fieldset',
    '#title' => t('Download links'),
    '#description' => t("This OAI request handler adds elements to the OAI records containing " .
        "direct links to download a file for each object. See the module's README for more information."),
    '#collapsible' => FALSE,
    '#collapsed' => TRUE,
  );
  $form['islandora_oai_download_links']['islandora_oai_download_link_cmodel_link_mappings'] = array(
    '#type' => 'textarea',
    '#title' => t('Content model to link mappings for download links'),
    '#description' => t('Enter, one per line, mappings for which datastream should be included ' .
      'in the download links provided to harvesters.'),
      '#default_value' => variable_get('islandora_oai_download_link_cmodel_link_mappings', 'islandora:sp_basic_image = OBJ'),
  );
  $form['islandora_oai_download_links']['islandora_oai_download_link_allowed_ips'] = array(
    '#type' => 'textarea',
    '#title' => t('Allowed IP ranges for full text download links'),
    '#description' => t('Enter the IP address ranges, one per line, of ' .
      ' harvesters that will be provided with download links. Separate the ' .
      ' low and high ends of each range with a colon, e.g. 111.111.111.111:222.222.222.222. ' .
      ' Asterisks are not allowed. Single IP addresses are also allowed, each on its own line.'),
      '#default_value' => variable_get('islandora_oai_download_link_allowed_ips', ''),
  );
  $form['submit']['#weight'] = 10;
  $form['#submit'][] = 'islandora_oai_download_link_handler_configuration_submit';
}
